//
//  SyncSource+Extension.swift
//  NXFitSync
//
//  Created by IRC Developer on 2024-04-03.
//

import Foundation
import HealthKit

internal extension SyncSource {       
    static func createFrom(_ sample: HKObject) -> SyncSource {
        let (deviceName, deviceOS) = parseDevice(sample.device?.name, sample.device?.hardwareVersion, sample.device?.manufacturer, sample.device?.hardwareVersion)
        let (appName, appIdentifier) = parseApp(sample.sourceRevision.source.name, sample.sourceRevision.source.bundleIdentifier)
        
        return SyncSource(
            deviceName: deviceName,
            deviceHardwareVersion: sample.device?.hardwareVersion,
            deviceManufacturer: sample.device?.manufacturer,
            deviceOS: deviceOS,
            appName: appName,
            appIdentifier: appIdentifier
        )
    }
    
    static func parseApp(_ name: String?, _ identifier: String?) -> (name: String?, identifier: String?) {
        if let sourceAppIdentifier = identifier, sourceAppIdentifier.hasPrefix("com.apple.health.") {
            return ("Fitness", "com.apple.health.")
        }
        
        return (name, identifier)
    }
    
    static func parseDevice(_ deviceName: String?, _ deviceHardwareVersion: String?, _ deviceManufacturer: String?, _ deviceOS: String?) -> (name: String?, OS: String?) {
        if let deviceManufacturer = deviceManufacturer, deviceManufacturer == "Apple Inc." {
            if let deviceHardwareVersion = deviceHardwareVersion, let mappedDevice = deviceMapping[deviceHardwareVersion] {
                return mappedDevice
            }
        }
        
        return (deviceName, deviceOS)
    }
    
    //TODO: NEED A BETTER WAY TO MANAGE THIS MAPPING THAT DOESN'T RELY ON SDK RELEASES.
    //List of devices: https://gist.github.com/adamawolf/3048717
    static let deviceMapping: Dictionary<String, (name: String, OS: String)> = [
        "iPhone1,1": ("iPhone", "iOS"),
        "iPhone1,2": ("iPhone 3G", "iOS"),
        "iPhone2,1": ("iPhone 3GS", "iOS"),
        "iPhone3,1": ("iPhone 4", "iOS"),
        "iPhone3,2": ("iPhone 4", "iOS"),
        "iPhone3,3": ("iPhone 4", "iOS"),
        "iPhone4,1": ("iPhone 4s", "iOS"),
        "iPhone5,1": ("iPhone 5", "iOS"),
        "iPhone5,2": ("iPhone 5", "iOS"),
        "iPhone5,3": ("iPhone 5c", "iOS"),
        "iPhone5,4": ("iPhone 5c", "iOS"),
        "iPhone6,1": ("iPhone 5s", "iOS"),
        "iPhone6,2": ("iPhone 5s", "iOS"),
        "iPhone7,1": ("iPhone 6 Plus", "iOS"),
        "iPhone7,2": ("iPhone 6", "iOS"),
        "iPhone8,1": ("iPhone 6s", "iOS"),
        "iPhone8,2": ("iPhone 6s Plus", "iOS"),
        "iPhone8,4": ("iPhone SE", "iOS"),
        "iPhone9,1": ("iPhone 7", "iOS"),
        "iPhone9,2": ("iPhone 7 Plus", "iOS"),
        "iPhone9,3": ("iPhone 7", "iOS"),
        "iPhone9,4": ("iPhone 7 Plus", "iOS"),
        "iPhone10,1": ("iPhone 8", "iOS"),
        "iPhone10,2": ("iPhone 8 Plus", "iOS"),
        "iPhone10,3": ("iPhone X", "iOS"),
        "iPhone10,4": ("iPhone 8", "iOS"),
        "iPhone10,5": ("iPhone 8 Plus", "iOS"),
        "iPhone10,6": ("iPhone X", "iOS"),
        "iPhone11,2": ("iPhone XS", "iOS"),
        "iPhone11,4": ("iPhone XS Max", "iOS"),
        "iPhone11,6": ("iPhone XS Max", "iOS"),
        "iPhone11,8": ("iPhone XR", "iOS"),
        "iPhone12,1": ("iPhone 11", "iOS"),
        "iPhone12,3": ("iPhone 11 Pro", "iOS"),
        "iPhone12,5": ("iPhone 11 Pro Max", "iOS"),
        "iPhone12,8": ("iPhone SE 2nd Gen", "iOS"),
        "iPhone13,1": ("iPhone 12 mini", "iOS"),
        "iPhone13,2": ("iPhone 12", "iOS"),
        "iPhone13,3": ("iPhone 12 Pro", "iOS"),
        "iPhone13,4": ("iPhone 12 Pro Max", "iOS"),
        "iPhone14,2": ("iPhone 13 Pro", "iOS"),
        "iPhone14,3": ("iPhone 13 Pro Max", "iOS"),
        "iPhone14,4": ("iPhone 13 mini", "iOS"),
        "iPhone14,5": ("iPhone 13", "iOS"),
        "iPhone14,6": ("iPhone SE 3rd Gen", "iOS"),
        "iPhone14,7": ("iPhone 14", "iOS"),
        "iPhone14,8": ("iPhone 14 Plus", "iOS"),
        "iPhone15,2": ("iPhone 14 Pro", "iOS"),
        "iPhone15,3": ("iPhone 14 Pro Max", "iOS"),
        "iPhone15,4": ("iPhone 15", "iOS"),
        "iPhone15,5": ("iPhone 15 Plus", "iOS"),
        "iPhone16,1": ("iPhone 15 Pro", "iOS"),
        "iPhone16,2": ("iPhone 15 Pro Max", "iOS"),
        "iPhone17,1": ("iPhone 16 Pro", "iOS"),
        "iPhone17,2": ("iPhone 16 Pro Max", "iOS"),
        "iPhone17,3": ("iPhone 16", "iOS"),
        "iPhone17,4": ("iPhone 16 Plus", "iOS"),
        "iPhone17,5": ("iPhone 16e", "iOS"),
        "iPod1,1": ("iPod 1st Gen", "iOS"),
        "iPod2,1": ("iPod 2nd Gen", "iOS"),
        "iPod3,1": ("iPod 3rd Gen", "iOS"),
        "iPod4,1": ("iPod 4th Gen", "iOS"),
        "iPod5,1": ("iPod 5th Gen", "iOS"),
        "iPod7,1": ("iPod 6th Gen", "iOS"),
        "iPod9,1": ("iPod 7th Gen", "iOS"),
        "iPad1,1": ("iPad 1st Gen", "iPadOS"),
        "iPad1,2": ("iPad 1st Gen", "iPadOS"),
        "iPad2,1": ("iPad 2nd Gen", "iPadOS"),
        "iPad2,2": ("iPad 2nd Gen", "iPadOS"),
        "iPad2,3": ("iPad 2nd Gen", "iPadOS"),
        "iPad2,4": ("iPad 2nd Gen", "iPadOS"),
        "iPad2,5": ("iPad mini 1st Gen", "iPadOS"),
        "iPad2,6": ("iPad mini 1st Gen", "iPadOS"),
        "iPad2,7": ("iPad mini 1st Gen", "iPadOS"),
        "iPad3,1": ("iPad 3rd Gen", "iPadOS"),
        "iPad3,2": ("iPad 3rd Gen", "iPadOS"),
        "iPad3,3": ("iPad 3rd Gen", "iPadOS"),
        "iPad3,4": ("iPad 4th Gen", "iPadOS"),
        "iPad3,5": ("iPad 4th Gen", "iPadOS"),
        "iPad3,6": ("iPad 4th Gen", "iPadOS"),
        "iPad4,1": ("iPad Air 1st Gen", "iPadOS"),
        "iPad4,2": ("iPad Air 1st Gen", "iPadOS"),
        "iPad4,3": ("iPad Air 1st Gen", "iPadOS"),
        "iPad4,4": ("iPad mini 2nd Gen", "iPadOS"),
        "iPad4,5": ("iPad mini 2nd Gen", "iPadOS"),
        "iPad4,6": ("iPad mini 2nd Gen", "iPadOS"),
        "iPad4,7": ("iPad mini 3rd Gen", "iPadOS"),
        "iPad4,8": ("iPad mini 3rd Gen", "iPadOS"),
        "iPad4,9": ("iPad mini 3rd Gen", "iPadOS"),
        "iPad5,1": ("iPad mini 4th Gen", "iPadOS"),
        "iPad5,2": ("iPad mini 4th Gen", "iPadOS"),
        "iPad5,3": ("iPad Air 2", "iPadOS"),
        "iPad5,4": ("iPad Air 2", "iPadOS"),
        "iPad6,3": ("iPad Pro 1st Gen", "iPadOS"),
        "iPad6,4": ("iPad Pro 1st Gen", "iPadOS"),
        "iPad6,7": ("iPad Pro 1st Gen", "iPadOS"),
        "iPad6,8": ("iPad Pro 1st Gen", "iPadOS"),
        "iPad6,11": ("iPad 5th Gen", "iPadOS"),
        "iPad6,12": ("iPad 5th Gen", "iPadOS"),
        "iPad7,1": ("iPad Pro 2nd Gen", "iPadOS"),
        "iPad7,2": ("iPad Pro 2nd Gen", "iPadOS"),
        "iPad7,3": ("iPad Pro 2nd Gen", "iPadOS"),
        "iPad7,4": ("iPad Pro 2nd Gen", "iPadOS"),
        "iPad7,5": ("iPad 6th Gen", "iPadOS"),
        "iPad7,6": ("iPad 6th Gen", "iPadOS"),
        "iPad7,11": ("iPad 7th Gen", "iPadOS"),
        "iPad7,12": ("iPad 7th Gen", "iPadOS"),
        "iPad8,1": ("iPad Pro 3rd Gen", "iPadOS"),
        "iPad8,2": ("iPad Pro 3rd Gen", "iPadOS"),
        "iPad8,3": ("iPad Pro 3rd Gen", "iPadOS"),
        "iPad8,4": ("iPad Pro 3rd Gen", "iPadOS"),
        "iPad8,5": ("iPad Pro 3rd Gen", "iPadOS"),
        "iPad8,6": ("iPad Pro 3rd Gen", "iPadOS"),
        "iPad8,7": ("iPad Pro 3rd Gen", "iPadOS"),
        "iPad8,8": ("iPad Pro 3rd Gen", "iPadOS"),
        "iPad8,9": ("iPad Pro 4th Gen", "iPadOS"),
        "iPad8,10": ("iPad Pro 4th Gen", "iPadOS"),
        "iPad8,11": ("iPad Pro 4th Gen", "iPadOS"),
        "iPad8,12": ("iPad Pro 4th Gen", "iPadOS"),
        "iPad11,1": ("iPad mini 5th Gen", "iPadOS"),
        "iPad11,2": ("iPad mini 5th Gen", "iPadOS"),
        "iPad11,3": ("iPad Air 3rd Gen", "iPadOS"),
        "iPad11,4": ("iPad Air 3rd Gen", "iPadOS"),
        "iPad11,6": ("iPad 8th Gen", "iPadOS"),
        "iPad11,7": ("iPad 8th Gen", "iPadOS"),
        "iPad12,1": ("iPad 9th Gen", "iPadOS"),
        "iPad12,2": ("iPad 9th Gen", "iPadOS"),
        "iPad13,1": ("iPad Air 4th Gen", "iPadOS"),
        "iPad13,2": ("iPad Air 4th Gen", "iPadOS"),
        "iPad13,4": ("iPad Pro 3rd Gen", "iPadOS"),
        "iPad13,5": ("iPad Pro 3rd Gen", "iPadOS"),
        "iPad13,6": ("iPad Pro 3rd Gen", "iPadOS"),
        "iPad13,7": ("iPad Pro 3rd Gen", "iPadOS"),
        "iPad13,8": ("iPad Pro 5th Gen", "iPadOS"),
        "iPad13,9": ("iPad Pro 5th Gen", "iPadOS"),
        "iPad13,10": ("iPad Pro 5th Gen", "iPadOS"),
        "iPad13,11": ("iPad Pro 5th Gen", "iPadOS"),
        "iPad13,16": ("iPad Air 5th Gen", "iPadOS"),
        "iPad13,17": ("iPad Air 5th Gen", "iPadOS"),
        "iPad13,18": ("iPad 10th Gen", "iPadOS"),
        "iPad13,19": ("iPad 10th Gen", "iPadOS"),
        "iPad14,1": ("iPad mini 6th Gen", "iPadOS"),
        "iPad14,2": ("iPad mini 6th Gen", "iPadOS"),
        "iPad14,3": ("iPad Pro 4th Gen", "iPadOS"),
        "iPad14,4": ("iPad Pro 4th Gen", "iPadOS"),
        "iPad14,5": ("iPad Pro 6th Gen", "iPadOS"),
        "iPad14,6": ("iPad Pro 6th Gen", "iPadOS"),
        "iPad15,3": ("iPad Air 11-inch 7th Gen", "iPadOS"),
        "iPad15,4": ("iPad Air 11-inch 7th Gen", "iPadOS"),
        "iPad15,5": ("iPad Air 13-inch 7th Gen", "iPadOS"),
        "iPad15,6": ("iPad Air 13-inch 7th Gen", "iPadOS"),
        "iPad15,7": ("iPad 11th Gen", "iPadOS"),
        "iPad15,8": ("iPad 11th Gen", "iPadOS"),
        "iPad16,1": ("iPad mini 7th Gen", "iPadOS"),
        "iPad16,2": ("iPad mini 7th Gen", "iPadOS"),
        "iPad16,3": ("iPad Pro 11 inch 5th Gen", "iPadOS"),
        "iPad16,4": ("iPad Pro 11 inch 5th Gen", "iPadOS"),
        "iPad16,5": ("iPad Pro 12.9 inch 7th Gen", "iPadOS"),
        "iPad16,6": ("iPad Pro 12.9 inch 7th Gen", "iPadOS"),
        "Watch1,1": ("Apple Watch 1st Gen", "watchOS"),
        "Watch1,2": ("Apple Watch 1st Gen", "watchOS"),
        "Watch2,6": ("Apple Watch Series 1", "watchOS"),
        "Watch2,7": ("Apple Watch Series 1", "watchOS"),
        "Watch2,3": ("Apple Watch Series 2", "watchOS"),
        "Watch2,4": ("Apple Watch Series 2", "watchOS"),
        "Watch3,1": ("Apple Watch Series 3", "watchOS"),
        "Watch3,2": ("Apple Watch Series 3", "watchOS"),
        "Watch3,3": ("Apple Watch Series 3", "watchOS"),
        "Watch3,4": ("Apple Watch Series 3", "watchOS"),
        "Watch4,1": ("Apple Watch Series 4", "watchOS"),
        "Watch4,2": ("Apple Watch Series 4", "watchOS"),
        "Watch4,3": ("Apple Watch Series 4", "watchOS"),
        "Watch4,4": ("Apple Watch Series 4", "watchOS"),
        "Watch5,1": ("Apple Watch Series 5", "watchOS"),
        "Watch5,2": ("Apple Watch Series 5", "watchOS"),
        "Watch5,3": ("Apple Watch Series 5", "watchOS"),
        "Watch5,4": ("Apple Watch Series 5", "watchOS"),
        "Watch5,9": ("Apple Watch SE", "watchOS"),
        "Watch5,10": ("Apple Watch SE", "watchOS"),
        "Watch5,11": ("Apple Watch SE", "watchOS"),
        "Watch5,12": ("Apple Watch SE", "watchOS"),
        "Watch6,1": ("Apple Watch Series 6", "watchOS"),
        "Watch6,2": ("Apple Watch Series 6", "watchOS"),
        "Watch6,3": ("Apple Watch Series 6", "watchOS"),
        "Watch6,4": ("Apple Watch Series 6", "watchOS"),
        "Watch6,6": ("Apple Watch Series 7", "watchOS"),
        "Watch6,7": ("Apple Watch Series 7", "watchOS"),
        "Watch6,8": ("Apple Watch Series 7", "watchOS"),
        "Watch6,9": ("Apple Watch Series 7", "watchOS"),
        "Watch6,10": ("Apple Watch SE", "watchOS"),
        "Watch6,11": ("Apple Watch SE", "watchOS"),
        "Watch6,12": ("Apple Watch SE", "watchOS"),
        "Watch6,13": ("Apple Watch SE", "watchOS"),
        "Watch6,14": ("Apple Watch Series 8", "watchOS"),
        "Watch6,15": ("Apple Watch Series 8", "watchOS"),
        "Watch6,16": ("Apple Watch Series 8", "watchOS"),
        "Watch6,17": ("Apple Watch Series 8", "watchOS"),
        "Watch6,18": ("Apple Watch Ultra", "watchOS"),
        "Watch7,1": ("Apple Watch Series 9", "watchOS"),
        "Watch7,2": ("Apple Watch Series 9", "watchOS"),
        "Watch7,3": ("Apple Watch Series 9", "watchOS"),
        "Watch7,4": ("Apple Watch Series 9", "watchOS"),
        "Watch7,5": ("Apple Watch Ultra 2", "watchOS"),
        "Watch7,8": ("pple Watch Series 10", "watchOS"),
        "Watch7,9": ("Apple Watch Series 10", "watchOS"),
        "Watch7,10": ("Apple Watch Series 10", "watchOS"),
        "Watch7,11": ("Apple Watch Series 10", "watchOS")
    ]
}
