//
//  ApiActivityType.swift
//  NXFitCore
//
//  Created by Neo eX on 2023-01-04.
//

import Foundation
import HealthKit

/// Mapping for the NXFit platform activity types.
public enum ApiActivityType : String, Codable {
    case other = "Other",
         aerobics = "Aerobics",
         americanFootball = "AmericanFootball",
         archery = "Archery",
         australianFootball = "AustralianFootball",
         badminton = "Badminton",
         baseball = "Baseball",
         basketball = "Basketball",
         beachVolleyball = "BeachVolleyball",
         biathlon = "Biathlon",
         boxing = "Boxing",
         calisthenics = "Calisthenics",
         cardioTraining = "CardioTraining",
         circuitTraining = "CircuitTraining",
         climbing = "Climbing",
         coreTraining = "CoreTraining",
         cricket = "Cricket",
         crossCountrySkiing = "CrossCountrySkiing",
         crossFit = "CrossFit",
         crossTraining = "CrossTraining",
         curling = "Curling",
         cycling = "Cycling",
         dancing = "Dancing",
         diving = "Diving",
         elliptical = "Elliptical",
         englishFootball = "EnglishFootball",
         fencing = "Fencing",
         frisbee = "Frisbee",
         golf = "Golf",
         gymnastics = "Gymnastics",
         handball = "Handball",
         handCycling = "HandCycling",
         hiit = "HIIT",
         hiking = "Hiking",
         hockey = "Hockey",
         horsebackRiding = "HorsebackRiding",
         iceSkating = "IceSkating",
         indoorVolleyball = "IndoorVolleyball",
         intervalTraining = "IntervalTraining",
         jumpingRope = "JumpingRope",
         kayaking = "Kayaking",
         kickboxing = "Kickboxing",
         lacrosse = "Lacrosse",
         meditation = "Meditation",
         mixedMartialArts = "MixedMartialArts",
         mountainBiking = "MountainBiking",
         pilates = "Pilates",
         polo = "Polo",
         preparationAndRecovery = "PreparationAndRecovery",
         racquetball = "Racquetball",
         rockClimbing = "RockClimbing",
         rowing = "Rowing",
         rugby = "Rugby",
         running = "Running",
         sailing = "Sailing",
         scubaDiving = "ScubaDiving",
         skateboarding = "Skateboarding",
         skating = "Skating",
         skiing = "Skiing",
         skyDiving = "SkyDiving",
         snowboarding = "Snowboarding",
         snowshoeing = "Snowshoeing",
         softball = "Softball",
         spinbike = "SpinBike",
         squash = "Squash",
         stairClimbing = "StairClimbing",
         stairClimbingMachine = "StairClimbingMachine",
         stationaryBiking = "StationaryBiking",
         strengthTraining = "StrengthTraining",
         stretching = "Stretching",
         surfing = "Surfing",
         swimming = "Swimming",
         tableTennis = "TableTennis",
         tennis = "Tennis",
         treadmill = "Treadmill",
         triathlon = "Triathlon",
         volleyball = "Volleyball",
         walking = "Walking",
         waterPolo = "WaterPolo",
         weightlifting = "Weightlifting",
         wheelchairRun = "WheelchairRun",
         wheelchairWalk = "WheelchairWalk",
         windsurfing = "Windsurfing",
         yoga = "Yoga"
}
